### PR TITLE
Use new signed requests format

### PR DESCRIPTION
**Pull request by jublo**
Requests are now appended with a `sig=xxxx` parameter calculated from a hash based on the endpoint (method called) and all parameters, sorted alphabetically by key, hashed with the client secret.

### CODE REVIEW

**Comment by johannesnagl** [comment]
successor of #141, #128.

**Comment by johannesnagl** [comment]
we tested this in production and it works like a charme! thx @jublo!

**Comment by jublo** [comment]
Will this get merged, thus?

**Comment by vinkla** [comment]
Thanks!

**Pull request merged**
