### PR TITLE
Add install info via composer

### PR DESCRIPTION
**Pull request by GuidoBR**
Installation info should be explicit at the README file.

Found this method at Packagist.

### CODE REVIEW

**Comment by vinkla** [comment]
This is great. Though, maybe you could update the version to `~2.0`? Using `dev-master` in production is  considered bad practice. We should help developers doing it right from the start.

I would even consider removing the JSON example and adding command line instructions instead.

```bash
composer require cosenary/instagram
```

**Comment by GuidoBR** [comment]
Done. It's really better now.

**Comment by cosenary** [comment]
Thanks @GuidoBR!

**Comment by vinkla** [comment]
Very nice!

**Pull request merged**
