### PR TITLE
Update Instagram.php

### PR DESCRIPTION
**Pull request by GMusliaj**
Added curl_setopt($ch, CURLOPT_HEADER, true);

### CODE REVIEW

**Comment by ftrrtf** [comment]
:+1:

**Comment by angelxmoreno** [comment]
was just about to create a PR for this! 
+1

**Comment by vinkla** [comment]
:+1:

**Comment by angelxmoreno** [comment]
how are people getting the lib to work under ver 2.3? without this PR the lib seems completely broken to me. Can we clean up the dev branch and have this pr be sent there?

**Comment by ramiroaraujo** [comment]
@angelxmoreno and all, I reverted back to the v2.3 tag and everything is working fine. You're probably using dev-master, which translates to the last code in master branch.

**Comment by angelxmoreno** [comment]
:+1: winning. thanks @ramiroaraujo

**Comment by vinkla** [comment]
Thanks for your contribution! Merged.

**Pull request merged**
